### ISSUE TITLE
Support `<code>` tags in the description/changelog sections

### ISSUE THREAD

**Issue by guihkx** [flathub-infra/website#1248]
According to the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-description), some HTML tags are permitted inside `<description>` tags, including `<code>`.

However, Flathub seems to be ignoring them:

- https://beta.flathub.org/apps/io.github.nuttyartist.notes

And here's the appdata file itself:

https://github.com/nuttyartist/notes/blob/0421737ace84142a5b50ce2dcb6a9df97ef8a60e/packaging/linux/common/notes.appdata.xml.in

**Comment by razzeee** [comment]
Working now, but please keep in mind, that they are probably not supported in the release description, at least that's not explicitly stated in the spec. It seems to work on our end, but gnome software for e.g. seems unhappy.

**Comment by guihkx** [comment]
I'll keep that mind. Thanks!

**Comment by razzeee** [comment]
Should be back working, but needs the app to be rebuild
