### ISSUE TITLE
The project_license field missing or disappears

### ISSUE THREAD

**Issue by barthalion** [flathub-infra/website#1694]
There have been plenty of publishing failures recently, all caused by flathub-hooks failing to get a non-error response from `/purchases/storefront-info`:

```
1 validation error for StorefrontInfo
response -> is_free_software
  value could not be parsed to a boolean (type=type_error.bool)
```

It seems there are different versions of this issue, manifested by the exception above.

Some projects define the licence but it gets stripped in appstream:

```
[📦 org.openrgb.OpenRGB share]$ grep project_lic /app/share/appdata/org.openrgb.OpenRGB.appdata.xml   <project_license>GPL-2.0-or-later</project_license>
```

Others don't define any, but how does it pass validation?

```
[📦 net.sourceforge.wxEDID ~]$ grep project_lic /app/share/appdata/net.sourceforge.wxEDID.appdata.xml  -c
0
```

I will be adding some duct tape but this needs more investigation.

**Comment by JakobDev** [comment]
> Others don't define any, but how does it pass validation?

[net.sourceforge.wxEDID has defined the projcet_license](https://github.com/flathub/net.sourceforge.wxEDID/blob/5a589bc4f5a6a59e5c1bd4cc2d14d5e2c2c99ee7/net.sourceforge.wxEDID.appdata.xml#L6)

**Comment by razzeee** [comment]
We haven't seen this for some time I think?
