### ISSUE TITLE
Page 1 of "Recently updated apps" is not being updated

### ISSUE THREAD

**Issue by laniakea64** [flathub-infra/website#1784]
https://flathub.org/apps/collection/recently-updated/1 has not been updated for some days now.  But seems only this one specific link is stuck: both the "Recently updated apps" section on [the homepage](https://flathub.org/), and [page 2](https://flathub.org/apps/collection/recently-updated/2) and later pages of "Recently updated apps", do appear to be getting updated?

Other collections don't seem to have this issue.

Thanks for anything you can do to resolve this :slightly_smiling_face:

**Comment by razzeee** [comment]
Yes, I'm aware of that. I think the cache is somehow stuck. Not sure how to get it unstuck. It might be connected to the change to axios.

**Comment by razzeee** [comment]
Should be good again, had someone with server access drop the cache.

https://nextjs.org/docs/pages/building-your-application/data-fetching/incremental-static-regeneration#self-hosting-isr
