### ISSUE TITLE
Flathub shows end of life Apps in Authored Apps

### ISSUE THREAD

**Issue by JakobDev** [flathub-infra/website#1905]
As the title says. These Apps are EOL but still shown.

![grafik](https://github.com/flathub/website/assets/15185051/44ec809a-c66e-43c6-87ac-a90f07675a44)

**Comment by razzeee** [comment]
I think we knew that. I don't remember the exact plan, but I think we want devs to be able to edit something on them?

Maybe @barthalion remembers

**Comment by JakobDev** [comment]
These Apps are all rebased. Why should I need to mange them?

**Comment by razzeee** [comment]
I think this is no longer the case. For better or for worse.
