### ISSUE TITLE
PipeWire sound server permission marks application as potentially unsafe

### ISSUE THREAD

**Issue by ilya-fedin** [flathub-infra/website#1919]
According to https://github.com/flatpak/flatpak/issues/5130#issuecomment-1272348665, `--filesystem=xdg-run/pipewire-0` is the right permission for PipeWire acting as sound server yet flathub website marks applications as potentially unsafe with the following: 
![](https://github.com/flathub/website/assets/17829319/2e7eaf59-6b9d-4068-bb39-5ead2c0d354e)

PulseAudio permission doesn't cause such a problem.

**Comment by orowith2os** [comment]
PipeWire isn't just a sound server - it handles screen sharing, cameras, and all sorts of multimedia devices too. It should 100% be marked as potentially unsafe. How it's marked as potentially unsafe is the topic for discussion here.

**Comment by ilya-fedin** [comment]
Do you mean flatpak applications should avoid pipewire and use pulseaudio to be safe? I want to get rid of this for my application, not a clearer statement. I don't think my application should be marked as such just because it uses the more modern API.

**Comment by orowith2os** [comment]
I don't *mean* anything - it's up to the apps to choose what they want to use here. But safety warnings don't really matter right now, until quite a few portals land (an expanded Device portal, for one).

**Comment by ilya-fedin** [comment]
> an expanded Device portal, for one

It seem to stuck for two years already?

**Comment by ilya-fedin** [comment]
I'd wonder what's the recommended approach to avoid application being marked as potentially unsafe for now :thinking:

**Comment by orowith2os** [comment]
> It seem to stuck for two years already?

Contributions welcome.

**Comment by razzeee** [comment]
@ilya-fedin can you try if this also happens in gnome software (ideally gnome software 45)

if it does happen there:
- open an issue over there, similar to https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2315 and let us know of that  issue

if it doesn't, I probably missed it when I implemended this.

**Comment by razzeee** [comment]
It would also be great to let us know which apps you were able to test this with, I'm not feeling like I should have to hunt this down :)

**Comment by ilya-fedin** [comment]
@razzeee I don't think I can, I'm a NixOS KDE user, installing GNOME software will likely be a big headache...

**Comment by razzeee** [comment]
@ilya-fedin I can probably check it for you, I have a vm and a laptop already on 45, but I will need an app with that permission set

**Comment by ilya-fedin** [comment]
https://github.com/search?q=org%3Aflathub%20--filesystem%3Dxdg-run%2Fpipewire-0&type=code

**Comment by razzeee** [comment]
Yeah, this seems to be an oversight in g-s too, I think. I'll open an issue over there.

**Comment by razzeee** [comment]
https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2329

**Comment by razzeee** [comment]
https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1811/diffs is the current state of gnome software

**Comment by ilya-fedin** [comment]
Do I understand right that pulseaudio access will be still displayed as safer than pipewire access?

**Comment by razzeee** [comment]
I don't think so, but can you point me to an example/finish-arg?

**Comment by ilya-fedin** [comment]
finish arg of what? pulseaudio access? `--socket=pulseaudio`. Almost every flatpak package has it yet flathub doesn't present it in any way nor marks application as potentially unsafe due to it, unlike pipewire.

**Comment by ilya-fedin** [comment]
It also allows to record the sound. Or apps like Discord wouldn't work.

**Comment by razzeee** [comment]
Created https://gitlab.gnome.org/GNOME/gnome-software/-/issues/2394

**Comment by ilya-fedin** [comment]
Lurking regarding the `--filesystem=xdg-run/pipewire-0` change in gnome-software I noticed https://gitlab.gnome.org/GNOME/gnome-software/-/commit/56c3a9b784da23f2a60f18b807bd31f3701dee78, is flathub going to do the same? It looks quite weird given that `--devices=all` provides access to all the /dev including /dev/dri and /dev/fb* that should give the screen grabbing (and likely also modifying) just as well as pipewire. I would expect that to be mentioned in the existing all-device access rather than a separate item.

**Comment by razzeee** [comment]
We can implement this to match g-s as far as I see now

**Comment by ilya-fedin** [comment]
Would be really nice if it means pipewire access wouldn't be treated as file access anymore

**Comment by rugk** [comment]
BTW I used this to spark the discussion a bit more about the actual issue laying behind: that apps can "secretly" record audio with a very innocently looking permission, as IMHO it is very relevant: https://github.com/flatpak/xdg-desktop-portal/discussions/1142#discussioncomment-11859336 / https://github.com/flatpak/flatpak/issues/6082

**Comment by ilya-fedin** [comment]
fwiw, snap has separate audio output/input plugs since a long time:
https://snapcraft.io/docs/audio-playback-interface
https://snapcraft.io/docs/audio-record-interface
