### ISSUE TITLE
Many app pages don't load until refresh

### ISSUE THREAD

**Issue by chrisawi** [flathub-infra/website#2005]
This is similar to #1648, but it's affecting many more pages this time.

Many links on the homepage are 404-ing, starting with https://flathub.org/apps/xyz.slothlife.Jogger

From the previous issue, most links on https://flathub.org/apps/search?q=gnome are now broken.

**Comment by razzeee** [comment]
The hope is, that https://github.com/flathub/website/issues/1931 could fix this, when we solve that.

**Comment by razzeee** [comment]
Hopefully fixed by https://github.com/flathub-infra/website/pull/2513
