### ISSUE TITLE
`<code>` blocks aren't being rendered

### ISSUE THREAD

**Issue by hwittenborn** [flathub-infra/website#2072]
For some reason `<code>` blocks aren't being rendered, as shown at https://flathub.org/apps/com.hunterwittenborn.Celeste:

![image](https://github.com/flathub/website/assets/74838472/dfe0ef83-8413-4ce4-b3d8-d33919a4213a)

It looks like [Flathub should support the functionality](https://github.com/flathub/website/issues/1248#issuecomment-1577685250), is there something I'm doing wrong with my app?

**Comment by razzeee** [comment]
No, it's not your fault. We had to revert the change to libappstream. It will be used in the future I'm just not sure when, as I can't do the change over.

**Comment by hwittenborn** [comment]
Do you know the reason the change was reverted in libappstream @razzeee? Was there some kind of buggy behavior with it or something?

**Comment by razzeee** [comment]
Yes, multiple, the worst was old ubuntu versions refusing to do anything flatpak. The other was screenshots being broken.

**Comment by hwittenborn** [comment]
Oh, was a new library being used as part of the ability to use `<code>` blocks? Or was it the `<code>` block support specifically that broke something?

**Comment by razzeee** [comment]
libappstream is a new library, so yes. It's what would then be used to create the files on the server.

**Comment by razzeee** [comment]
This should now be working, but needs a rebuild
