### ISSUE TITLE
Archived flathub.org repository links to wrong new repo

### ISSUE THREAD

**Issue by Maltimore** [flathub-infra/website#2368]
The repository at https://github.com/flathub/flathub.org is archived and links to https://github.com/flathub-infra/linux-store-frontend which is also archived. The latter one doesn't link to a new repo, but I assume it is this one?

Maybe one could let both repos directly reference this repo, or whichever is the replacement.

**Comment by razzeee** [comment]
This is the correct place, but github has no way of changing archived repos anymore, so we can't do anythnig about it.

I guess the real question would be, how you ended up in the archived one in the first place, as it's usually hidden from search and listings.

**Comment by Maltimore** [comment]
Okay, good to know that archived repos can't be changed at all anymore.
Unfortunately I don't remember how I found the archived repo, but I'm pretty sure I didn't do anything "clever". Something linked me to it.
Since I don't remember how I found it, I think this issue should be closed. If I remember, I'll reopen.
