### ISSUE TITLE
Setup instructions for Windows

### ISSUE THREAD

**Issue by sonnyp** [flathub-infra/website#2376]
Apparently Flatpak works just fine with WSL 
A contributor is using WSL to run and contribute to Workbench :exploding_head: 

I don't have access to a Windows / WSL computer so I can't do it myself ATM
We could consider adding instructions for Windows / WSL as a draft or with a warning.

A potential next step would be some kind of signed `.exe` to take care of it all.

https://floss.social/@sonny/111715511122341006

**Comment by razzeee** [comment]
Please report at https://github.com/flatpak/flatpak.github.io/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
