### ISSUE TITLE
App picks papercuts

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#2417]
A few things that would be nice to have on the backend:

- [x] The carousel disappears anytime you change something, which is annoying and not very helpful when picking apps. Instead, I'd keep the carousel always visible and switch to the page with the app I just set.
- [ ] Chooser list papercuts:
  - [x] It'd be helpful to have a bit more information for each of the apps in the chooser lists, including app icon, summary, last updated, and if/how long ago it was featured previously. OTOH the app ID doesn't seem useful for this.
  - [x] ~~It could also be useful to filter/gray out items that have been featured recently (e.g. in the past 3 months)~~
  - [ ] I'd make the popover larger, so that you can see at least 8-10 items if the screen is large enough
  - [ ] Perhaps we could have a third line with when the app was last featured? Quick experiment (icon size bumped to 32 to balance out the layout):
    
![image](https://github.com/flathub-infra/website/assets/1908896/e5486822-40d2-4fb1-bc4b-24cfc376b34e)

![image](https://github.com/flathub-infra/website/assets/1908896/3144935d-5c46-425d-91f0-3ec0c598c103)

- [ ] ~~There's no way to reset fields to empty~~

General UI papercuts with the carousel:

- [x] I'm no longer sure if we should launch without some kind of background color, it's just way less visually interesting in white. Could we maybe extract a color from the icon server-side?
- [x] ~~We have to do something different with cropping/spacing for fullscreen screenshots, maybe a vertical offset and a border radius of 18px or so?~~ No fullscreen screenshots until we have libappstream

![image](https://github.com/flathub-infra/website/assets/1908896/394e1def-3785-4388-99aa-8bfc7301c24c)

- [ ] Arrow button papercuts:
  - [x] The arrow icon is too large, I'd make it about half the current size
  - [x] I'd make the arrow text color rather than blue
  - [x] It's very easy to accidentally click the banner instead of an arrow, in large part because the arrow buttons have no hover state. I'd give them a circular button shape on hover, similar to the carousel in Software
  - [x] The button is a little bit too small now, I'd make the icon a few pixels larger and increase the padding around it
  
![image](https://github.com/flathub-infra/website/assets/1908896/79382321-7f92-4588-9170-db416389639f)

- [x] The hover effect with saturation looks glitchy on the icons, I'd just drop it for now

- [x] ~~I wonder if we should make the banner a little bit taller at the largest breakpoints, this looks a bit cramped with the screenshot almost touching the top:~~ Never mind, looks like Foliate has a custom shadow

![image](https://github.com/flathub-infra/website/assets/1908896/e41c4430-b313-4f98-a3d6-6a19003d1356)

**Comment by razzeee** [comment]
1. Should be fixed
2. Will work on this later
3. I don't think we want to reset stuff to be empty again, in general, we'll need to make sure, that we have 5 apps for each week (it shouldn't crash, but it would be lame)
4. I don't even think, that we can rely on this, after we're getting the regular metadata when we have libappstream. There might always be an app without it set. Or worse, that looks bad in light or dark? 
5. That would only work for apps like kodi, where the aspect ratio is correct, but border radius would work nowhere else. I would think we should try to not pick these, till we have libappstream.
6. These should be addressed.

**Comment by razzeee** [comment]
Will close for now

**Comment by bertob** [comment]
Should I open separate issues for the remaining items?
