### ISSUE TITLE
The "request review" button doesn't have any indication what it is about on mobile

### ISSUE THREAD

**Issue by sgued** [flathub-infra/website#2455]
The request review button  makes sense on desktop, but on mobile it is just an icon with no label, and there doesn't seem to be any indication on what it does when viewing the site on mobile.

![image](https://github.com/flathub-infra/website/assets/51865119/7db4f920-13c9-4dcd-b46f-baf544ba9ab6)

![image](https://github.com/flathub-infra/website/assets/51865119/0a154d6d-47fb-4509-8ffe-d5a99ffe3314)

There also should be some more information regarding what "request review" means, even on desktop. Are the reviews done by humans? I did not find any documentation on this process.. If so, sorry for clicking it to understand what it does.

Maybe a modal dialog should open when clicking the button, asking for confirmation and informing on what a review consists of.

That would solve both issues.

**Comment by razzeee** [comment]
Yeah, agreed, this was already brought up, but there wasn't an issue, so thanks for creating this.

I think we want the modal, with translated explanations and maybe even a comment box.
