### ISSUE TITLE
Wrong text alignment for StackedListBox items in RTL

### ISSUE THREAD

**Issue by danialbehzadi** [flathub-infra/website#2460]
When switching to an RTL locale, the items in [StackedListBox](https://github.com/flathub-infra/website/blob/main/frontend/src/components/application/StackedListBox.tsx) is shown left-aligned.

I could fix this issue locally by adding `text-align: start;` to `leading-none` class. But I'm not an expert on scss to fix it upstream.

**Comment by razzeee** [comment]
Thanks for raising this, I've prepared a fix
