### ISSUE TITLE
Add the sq locale to the project

### ISSUE THREAD

**Issue by ujdhesa** [flathub-infra/website#2532]
Hello!

I’d like to add sq locale to the project. I’m close to completing the translation of the main file (93% as of today). Do you need a pull request? Or the translations are commited in some other platform.

Thanks in advance!

**Comment by ujdhesa** [comment]
I forgot that I know the answer about any translation platform: https://hosted.weblate.org/projects/flathub/frontend/

The reason why I wasn’t able to add any translation there is that the locale file appears completed, even though it is empty.

**Comment by razzeee** [comment]
I'm not sure how that works, but at this point, I think it's a weblate issue, that they would need to look at.

**Comment by razzeee** [comment]
It's seems correct now
