### ISSUE TITLE
Re-imagine landing page

### ISSUE THREAD

**Issue by razzeee** [flathub-infra/website#2553]
The content of the landing page needs restructuring

- The recently added/recently updated is not relevant to normal users 
	- It's relevant to admins and news outlets, so we should keep it, but does not have to be on the main page
- Is it time to not show verified on there anymore?
- Would a tabbed layout work better?
- Could kill the `more` button somehow?

**Comment by scottjenson** [comment]
If I can add a bit of additional information, the idea is to provide a simpler navigation structure. Today the navigation with the MORE button makes for a slightly tedious nav experience: 1) Pick a MORE button 2) look/page/look again 3) Back button to pick another MORE button.

If there was some type of tabbed approach (there are a few ways to do this) the user could just go tab, look, tab, look, etc. It's just an easier way to quickly go through the apps. It also has the benefit of removing all of the MORE buttons. 

Note, depending on how many apps are in each section, they may need to page but the goal is to have the number of items in each tab area larger than today so depending on how you sort the items in each tab, the user could see quite a few before needing to page. The goal is that MOST of the time, the user would just need to use the Tabs (with maybe some scrolling)

**Comment by razzeee** [comment]
This is done now
