### ISSUE TITLE
Ensure website is aware of the new custom tag

### ISSUE THREAD

**Issue by barthalion** [flathub-infra/website#2557]
> Hmm, yeah, I guess I must have implemented it first with `<custom>`, then realized it's not what appstream-glib does. @razzeee we're going to have to switch backend and frontend to use the new field too at some point.

_Originally posted by @barthalion in https://github.com/flathub-infra/flat-manager-hooks/issues/101#issuecomment-1928905714_

**Comment by razzeee** [comment]
Worst case this needs to be done before libappstream, but I'll try to get to it this week

**Comment by barthalion** [comment]
Yeah, we should do that earlier. I can handle the backend part.

**Comment by razzeee** [comment]
I guess we also handle both https://github.com/flathub-infra/website/blob/main/backend/app/utils.py#L216

guess custom will just overwrite stuff from metadata, which should be fine

**Comment by barthalion** [comment]
Yeah, I guess we're backwards compatible after all.
