### ISSUE TITLE
flathub.org automatically redirects to Italian site

### ISSUE THREAD

**Issue by 1bcb** [flathub-infra/website#2669]
Steps to reproduce:
1)Set your operating system and browser to prefer US English.
2)Launch `flathub.org`

Expected result: The English US version of Flathub loads.
Actual result: The site redirects to `flathub.org/it`.

System information: 
I have reproduced the issue on the following browsers:
Firefox 123.0.1 (Flatpak)
Librewolf 123.0-1 (Flatpak)
Gnome Web 45.2 (Flatpak)
Chromium 121 (Flatpak)
Netsurf 3.10 (Deb)
Kiwi for Android 121
Chrome for Android 122

All my browsers and operating systems are set to prefer US English sites, and no other site is redirecting me to Italian.

Workaround: Directly entering `flathub.org/en` into the address bar loads the English page.

**Comment by razzeee** [comment]
As far as I understood, this was resolved by the admins.
