### ISSUE TITLE
Build gets held for review incorrectly

### ISSUE THREAD

**Issue by guihkx** [flathub-infra/website#2705]
Hi,

I maintain the [IRPF 2022](https://github.com/flathub/br.gov.fazenda.receita.irpf2022) app on Flathub. A few hours ago, I merged [a PR](https://github.com/flathub/br.gov.fazenda.receita.irpf2022/pull/15) that switched to `extra-data` sources, and that caused the build to be held for review (which is fine):

<details>
<summary>Screenshot</summary>

![image](https://github.com/flathub/flathub/assets/626206/0bcc8763-99fc-4440-a004-2624a9191fda)
</details>

A bit later, the build gets accepted:

<details>
<summary>Screenshot</summary>

![image](https://github.com/flathub/flathub/assets/626206/f7dc9a16-c619-4701-9d5b-d98eafb6b86f)
</details>

A few hours later, I merged [another PR](https://github.com/flathub/br.gov.fazenda.receita.irpf2022/pull/16) that simply removes a file, but that caused the build to be held for review again, for the same reason as the first time, i.e. switching to `extra-data`:

<details>
<summary>Screenshot</summary>

![image](https://github.com/flathub/flathub/assets/626206/c278a7cc-997f-40c6-9691-e45df113ff6f)
</details>

**Comment by hfiguiere** [comment]
This is expected. We have a series of checks to gets reviewed. This work as advertised.

Just be patient, we are not a trillion dollars gatekeeper, we are just a bunch of volunteers.

**Comment by hfiguiere** [comment]
might have been a race condition whereas the new build was not yet published.

**Comment by razzeee** [comment]
Yeah, at the point of deciding if something needs review it will always compare to the currently published app. I think that was the case in this moment, but it's hard to know, being able to dig through the logs.

So IMO, not something we can fix (here)

**Comment by guihkx** [comment]
Gotcha, thank you both.

I'll close this then.
