### ISSUE TITLE
Add Kabyle language

### ISSUE THREAD

**Issue by BoFFire** [flathub-infra/website#2708]
Hello,

I added Kabyle language via Weblate but the strings appear to be 0. Can you help to create `kab` with empty template and sync that with Weblate to be able to translate?

Screenshot here : https://mstdn.fr/@ButterflyOfFire/112090025162575445

Check this PR where Kabyle is empty : https://github.com/flathub-infra/website/pull/2707/files

Thanks

**Comment by gunchleoc** [comment]
What's your fallback locale for datetime? `ar-DZ`? Full list is here: https://github.com/date-fns/date-fns/tree/main/src/locale

**Comment by BoFFire** [comment]
Hello @gunchleoc 

> What's your fallback locale for datetime? `ar-DZ`? Full list is here: https://github.com/date-fns/date-fns/tree/main/src/locale

Not `ar-DZ` but English `en` or `en-US`should be okay.

**Comment by gunchleoc** [comment]
@BoFFire PR is done, please double-check: https://github.com/flathub-infra/website/pull/2709

I found some more dependencies, in case you want to translate those too, here's the list:

- https://github.com/michaelwittig/node-i18n-iso-countries/tree/master/langs
- https://github.com/i18next/next-i18next (doesn't seem to need translations
- https://github.com/date-fns/date-fns/tree/main/src/locale

**Comment by BoFFire** [comment]
Hi @gunchleoc 
Thank you ! I will translate the other linked projects. I'm adding them to my local translation queue.

**Comment by razzeee** [comment]
You should be able to translate it now, seems to show up fine on weblate

**Comment by BoFFire** [comment]
Thank you @razzeee and @gunchleoc I started with 12% translation.
