### ISSUE TITLE
Support filtering by runtime

### ISSUE THREAD

**Issue by ssokolow** [flathub-infra/website#2750]
I have strong opinions on my UIs and, as a KDE user, I find the growing UI-design alienness and shrinking customizability of GTK apps to be a deal-breaker... and given how many of them there are on Flathub, that's a discouragement to using Flathub because of how many I have to middle-click and then triage via their screenshots.

As a proxy for filtering based on UI type which doesn't require packages be retrofitted with new metadata, please consider supporting filtering based on the runtime the application depends on, so I can just check `org.freedesktop.Platform` and `org.kde.Platform` and anything else non-`org.gnome.Platform` that shows up rather than feeling demotivated to check for new apps I might want.

**Comment by bbhtt** [comment]
You can do this by going to https://flathub.org/statistics and clicking the bar graph of the corresponding runtime.

It's not exposed in search or anywhere else though.

**Comment by ssokolow** [comment]
Discoverability aside, I see two problems with that which affect me personally:

1. It doesn't appear to have a way to let me do version-independent filtering
2. It won't combine with #1910 when that gets fixed.

**Comment by razzeee** [comment]
I don't think we want this.

In general, you should be fine searching whatever you're looking for and maybe adding a `kde` to the end. Most apps that are looking like that will have it somewhere in the metadata, otherwise they are irrelevant for you anyway.

**Comment by ssokolow** [comment]
But I don't want KDE, I want "not GTK".

I'm fine with other toolkits as long as they can be made to look reasonably decent in the context of Breeze (eg. I have a `kde_breeze.reg` color scheme for Wine) and continue the UI design lineage started by Classic Mac OS and Windows 95.

**Comment by razzeee** [comment]
IMO that's not possible anyway.

**Comment by ssokolow** [comment]
Extending the existing filter UI so I can manually check every checkbox in the category except `org.gnome.Platform` would be an acceptable proxy.

**Comment by razzeee** [comment]
Runtimes should be irrelevant for average users, so we shouldn't confuse them with that in our search UI.

**Comment by ssokolow** [comment]
Call it "Ecosystem: KDE/GNOME/Other" if you want.

Failing that, is Flathub's API designed in a way where I could write a tool that performs a search, grabs metadata for each result, filters out any which use `org.gnome.Platform`, and then presents me with a PyQt `QListWidget` in icon-grid mode full of candidate tabs to open without getting blocked for excessive requests or would I need to do something like requesting the entire metadata database slowly over the course of a week and then caching it with the assumption that icons and runtimes never change?

**Comment by ssokolow** [comment]
Also good to know but, again, I'm trying to search for "all runtimes except ..." so, unless I'm writing some kind of tool to run multiple searches locally and then combine them for display, I don't see how that would help. (Or, if it supports multiple ORed-together filters, a tool to automatically grab the list of runtimes in use and build such a search.)

**Comment by razzeee** [comment]
Call the search endpoint https://flathub.org/api/v2/docs#/app/post_search_search_post it also returns the used runtime
