### ISSUE TITLE
Unverified badge tweaks

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#2818]
In actual use there are a few things that I feel could be improved about the "unverified" badge:

- It needs a bit more vertical spacing above the badge (something like 3px should work)
- The orange is maybe a bit too strong for what we're trying to get across, maybe yellow with dark text would be better?

![image](https://github.com/flathub-infra/website/assets/1908896/3125c11d-c431-4b37-a24d-7583046e29f6)

Quick experiment in Inspector:

![image](https://github.com/flathub-infra/website/assets/1908896/16001dd5-14d5-4a17-b0d0-33653eb6fc34)

**Comment by razzeee** [comment]
Hard agree on yellow

**Comment by razzeee** [comment]
The vertical spacing at the moment should be consistent with the verified badge (but that's not a badge visually)

**Comment by bertob** [comment]
Maybe we should make that a badge as well?

**Comment by razzeee** [comment]
Could work, depends on the design

**Comment by bertob** [comment]
Actually, a bit more spacing would look better in the other case as well (here I just added 3px top margin in Inspector):

![image](https://github.com/flathub-infra/website/assets/1908896/63dfd1e9-5d69-4755-aa8f-d39c2b32f2d0)

**Comment by vizrbo** [comment]
Hmm, somehow [the latest commit](https://github.com/flathub-infra/website/commit/c4d7e9895f41a76d754191b6cea9b35631fc65a9) got rid of the "verified" badge completely? @razzeee 

![image](https://github.com/flathub-infra/website/assets/133123008/b684590b-1aba-48f2-8968-1b009ec9fd12)
![image](https://github.com/flathub-infra/website/assets/133123008/72b908bf-dd66-40bd-801b-de1734a3195d)
