### ISSUE TITLE
Refresh “About” page

### ISSUE THREAD

**Issue by cassidyjames** [flathub-infra/website#2839]
Brought up when we were talking about links to verification information in Matrix. The current [about page](https://flathub.org/about) is pretty text-heavy and repeats some information that's better served (and more easily updated) by the docs site.

I'd be happy to rework the content there and help determine what content belongs on `/about` and what belongs at `docs.`

**Comment by cassidyjames** [comment]
Forgive the crude GitHub Markdown and emoji based layout, but I would put together something like this; the goal is communicate "What is Flathub and why should you care," and then to provide plenty of launching-off points to other relevant spaces instead of trying to answer everything else here.

---

# The Linux App Store

Whether you're a user looking for apps or a developer looking to reach more users, **Flathub is the best choice for apps on Linux.**

For Users | For Developers
--------- | --------------
**All the apps you want** — From big names you’d expect to fresh indie developers, Flathub has thousands of apps to meet your needs | **Reach millions of users** — Flathub comes out of the box on multiple Linux distros, is [easily installable]() on the rest, and has over a million active users
**Transparent safety** — Clearly see when an app is [verified](#) as coming from its developer, what permissions it requires, and whether or not it's open source and auditable | **Independent & transparent** — We’re a grassroots open source community stewarding the best of what the ecosystem has to offer
**Tastefully curated** — Discover interesting, quality apps across Flathub with our staff curation that showcases the best on offer _*Coming soon_ | **Clear docs & guidance** — Extensive [documentation](#), thousands of public app manifests, and a large community means you’re always able to get help
**Apps for you where you are** — Whether you’re on a Steam Deck, a powerful Linux workstation, a Raspberry Pi, or the rare Linux phone; Flathub has apps for you | **Native app store integration** — Forget web downloads; Flathub delivers apps and [updates](#) to users in their native app store client where they'd expect
[Set Up Flathub →](#) | [Publish Your App →](#)

---

## Get in Touch

Press | Security & Legal | Developers & Users
----- | ---------------- | ------------------
We're always happy to answer questions from and arrange interviews with journalists and tech writers | We take security reports and legal issues very seriously | Connect with the team and other members of the community to ask questions and share your expertise
[📰 Read Announcements](#) | [✉️ Report Security Concern](#) | [🗨️ Chat on Matrix](#)
[⬇️ Download Press Kit](#) | [✉️ Report Legal Issue](#) | [🗣️ Join Discourse Forum](#)
[✉️ Contact for Press Inquiries](#) | |

---

## Acknowledgements

Flathub wouldn't be possible without the generous support of the following organizations and individuals.

### Infrastructure & Development

- Codethink
- Cloud Native Computing Foundation
- Fastly
- Mythic Beasts
- Prerender.io
- Scaleway

### Financial Sponsors & More

- Alex Larsson
- Andreas Nilsson
- Arun Raghavan
- Bartłomiej Piotrowski
- Christian Hergert
- Christopher Halse Rogers
- Cosimo Cecchi
- Emmanuele Bassi
- G Stavracas Neto
- Jakub Steiner
- James Shubin
- Joaquim Rocha
- Jorge García Oncins
- Lubomír Sedlář
- Nathan Dyer
- Nick Richards
- Mario Sanchez Prada
- Matthias Clasen
- Michael Doherty
- Robert McQueen
- Zach Oglesby

**Comment by razzeee** [comment]
Can we split get in touch to a press page and a contact page?

**Comment by cassidyjames** [comment]
@razzeee we could, but those would end up being very short pages; I don't think it hurts to include them in one place, but I don't feel strongly.

**Comment by razzeee** [comment]
Any layout at tailwind ui https://tailwindui.com/components you think would fit this?

**Comment by cassidyjames** [comment]
@razzeee it sort of made me think of a pricing section, but I don't think that exact styling is what I'd want. I'm throwing something onto my site to get an idea out there (without spending too much time on exact styling), but you can totally Tailwind-ify it using whatever components make sense to you. :)

**Comment by cassidyjames** [comment]
@razzeee here's [a little HTML mockup](https://cassidyjames.com/about-flathub/) ([source](https://github.com/cassidyjames/cassidyjames.github.io/blob/main/about-flathub.html)), feel free to go wild! I'll also poke at Tailwind a bit to see if there are specific patterns I think make sense!

**Comment by thatLeaflet** [comment]
I like the new changes, but I have a nitpick regarding the automatic updates part. As it currently stands, flatpak relies on third party stores to handle those updates. But it would be nice if upstream flatpak shipped a systemd service to handle updates too.

For one, not all distros, desktops, or window managers come with GUI stores that can handle automatic flatpak updates. Notably, installing flatpak on Ubuntu will not have automatic updates unless Gnome Software is also installed with the flatpak plugin; but this isn't the nicest solution because then there would be two software stores installed. For another, I've tried using Gnome Software in WMs (I believe in Fedora Silverblue with Sway), but it wasn't the best experience since Gnome Software didn't really integrate with Sway well.

A systemd update service would help these two use cases well.

**Comment by cassidyjames** [comment]
@thatLeaflet most of that is off-topic for Flathub, but we do note in the linked documentation,

>Neither Flathub nor Flatpak dictate the update policy on end-user machines; instead, their OS and app store client (like GNOME Software or KDE Discover) determine the available options, and ultimately it's up to the user's preferences.

But across most distros, automatic updates _are_ supported. We could hedge a bit more and just say "updates" on this page, I guess.

**Comment by razzeee** [comment]
I think I would like it to be a bit more clearly separated, it's kinda hard to read in parts - might be fixable with some more padding / maybe doing cards

Would have prefered the layout to be done in our penpot :/

**Comment by razzeee** [comment]
Some of these changes will land with https://github.com/flathub-infra/website/pull/3130 

I'm still looking for a way to place the docs in there or even have them linked in the header

**Comment by razzeee** [comment]
@cassidyjames do you think there is anything in https://github.com/flathub-infra/website/issues/1587 we should get into here?
