### ISSUE TITLE
Mark apps that use online (and maybe offline) LLM/AI features

### ISSUE THREAD

**Issue by forteller** [flathub-infra/website#2869]
I think Flathub should implement an official way for apps to indicate if they're using at least online AI/LLM features, and require all apps using such to disclose which type. This should be displayed prominently, like the verified/unverified badge or the "potentially unsafe" or "community built" thingies.

I don't want to install and run the app before finding I can't use it b/c it's sending my data to the most evil corps (IMHO) in the world.

Apps using this offline should possibly also be marked. It's kinda like the "why have an unverified badge" thing: If they mention their AI features in their description, or has a name hinting about it, or you've heard rumors from elsewhere, but there's no official info about whether it's on- or offline, then that could create uncertainty. And some might not want to use offline models either.

Thank you for listening, and for all your really great and important work!

**Comment by razzeee** [comment]
This needs to happen in appstream to be useful https://github.com/ximion/appstream/issues

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub-infra/website/issues/2869#issuecomment-2293969909

@razzeee, https://github.com/ximion/appstream/issues/652#issue-2471052438.
