### ISSUE TITLE
Filter apps by cpu architecture

### ISSUE THREAD

**Issue by Intranox** [flathub-infra/website#3014]
I have a Raspberry Pi where I'm trying Flatpak, it would be nice to be able to filter the apps on flathub by architecture so that I can only see the ones that can actually run on arm64.

**Comment by bbhtt** [comment]
This is already possible

![image](https://github.com/flathub-infra/website/assets/62639087/2c99249c-05dc-4bda-b222-9d81a004e018)

**Comment by Intranox** [comment]
> This is already possible
> 
> ![image](https://private-user-images.githubusercontent.com/62639087/324262198-2c99249c-05dc-4bda-b222-9d81a004e018.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTY3MDYsIm5iZiI6MTcxMzcxNjQwNiwicGF0aCI6Ii82MjYzOTA4Ny8zMjQyNjIxOTgtMmM5OTI0OWMtMDVkYy00YmRhLWIyMjItOWQ4MWEwMDRlMDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE2MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmNDBmNjk2YmNkZTdmMWZlMGYyYWY3OTAwODQ4MDJmZjUxMWY3MThiY2MzNTQwYzAyN2NiNDlkZTgzYzc3YTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nCBy1TCzyVkOPKgAxxQUv0RkbZePeMhwAacawj5YoYk)

Thank you very much, I didn't think you could do a search without specifying a query string and therefore including all the apps.

**Comment by Intranox** [comment]
@bbhtt the only thing that limits this solution is due to the fact that a maximum of 250 apps are displayed in the search, this means that you cannot actually see all the apps for the chosen architecture relating to categories that exceed this threshold

**Comment by razzeee** [comment]
Why would you need more then 250 per category? What are you trying to do?

**Comment by Intranox** [comment]
> Why would you need more then 250 per category? What are you trying to do?

What I would like to do is to be able to view the apps that are available for a Raspberry and that is for the arm64 architecture. For example, I might be interested in seeing which apps are present in the "Utilities" category, but there are 591 apps of which I can only view 250. In other words, I would like to see the categories with the possibility of seeing only those compatible with a particular architecture, currently this can be done through the category route but there are also x86_64 apps, so I have to enter the page every time and scroll to see if the app is also available for arm64

**Comment by razzeee** [comment]
Same as https://github.com/flathub-infra/website/issues/1910 then
