### ISSUE TITLE
Clean up font sizes on cards

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#3028]
Currently we're using two font sizes for small text on cards, somewhat arbitrarily:
- Description on featured banner: 14px
- "App of the Day": 16px
- App of the day description: 16px
- "Get the latest versions of all your favorite apps, for any Linux distribution": 16px
- Tabs: 16px
- Title on regular app cards: 16px
- Summary on regular app cards: 14px

It'd be good to clean this up a bit, either by using the same size for all of them or by having a clear rule which size to use where.

![image](https://github.com/flathub-infra/website/assets/1908896/15872216-606d-4ca2-b8fa-f5ec37515457)

**Comment by razzeee** [comment]
I think that the font being bigger on the hero/highlight elements then on the app cards is fine.

The only thing I think that would make sense, is aligning description on featured banner to 16px to harmonize it between the other description texts.

**Comment by bertob** [comment]
> I think that the font being bigger on the hero/highlight elements then on the app cards is fine.

Not sure, I'd have tried going the other way and making them all 14, that'd also help to avoid strings wrapping too early e.g. on the app of the day card. The question is at that point, why not do it for the tabs as well?

**Comment by razzeee** [comment]
I think it's fine like this. The only one that's "surprising" might be the `Get the lastest versions...` text, as that is slightly bigger compared to other description texts.
