### ISSUE TITLE
Api to get newest app version

### ISSUE THREAD

**Issue by Core447** [flathub-infra/website#3119]
Is there a way to get the current/newest version of an app by its id via an api call?

**Comment by razzeee** [comment]
Releases are part of the basic appstream data https://flathub.org/api/v2/appstream/org.gnome.gitlab.YaLTeR.VideoTrimmer

**Comment by Core447** [comment]
Ok, thanks! In the meantime I found `https://flathub.org/api/v1/apps/app_id`, is there any disadvantage of using v1?

**Comment by razzeee** [comment]
it will be removed at some point

**Comment by Core447** [comment]
Ok
