### ISSUE TITLE
[About Page] Mobile Formatting Issues

### ISSUE THREAD

**Issue by RacerBG** [flathub-infra/website#3144]
The following issues appeared after the redesign of the page:

1. Two issues with the formatting due to horizontal orientation of the device (the "Developers & Contributors" is cut in half and the formatting of the names is incorrect) and one issue with the formatting of the names due to vertical orientation.
2. The color of the names with the light theme is unreadable (I do not have a screenshot with it).

![Screenshot_2024-05-06-01-40-05-606_com android chrome](https://github.com/flathub-infra/website/assets/68707872/ba8e0d5b-a01a-4a75-8861-c61c301912a5)
![Screenshot_2024-05-06-01-40-23-317_com android chrome](https://github.com/flathub-infra/website/assets/68707872/08951bd7-d888-4847-95e4-e62627448a17)
![Screenshot_2024-05-06-09-44-23-310_com android chrome](https://github.com/flathub-infra/website/assets/68707872/2a5843f0-ab07-49c4-b0c2-bb56117fe075)

**Comment by razzeee** [comment]
![image](https://github.com/flathub-infra/website/assets/5943908/7656d1b0-5a20-444d-b4ea-b7ad2fd6e202)

**Comment by razzeee** [comment]
Light mode was corrected

**Comment by RacerBG** [comment]
Another small issue which I had noticed on both the desktop and mobile version (on the press information section):

![Screenshot 2024-05-12 at 18-14-58 Относно Flathub](https://github.com/flathub-infra/website/assets/68707872/257d7a9f-6f94-4f0b-8151-aaa6140378eb)
![Screenshot_2024-05-12-18-18-10-922_com android chrome](https://github.com/flathub-infra/website/assets/68707872/94a89fe6-0abb-4941-9a0a-9c460bf50029)

**Comment by razzeee** [comment]
I have no idea what you think the problems here are. It's very unclear and thus probably unactionable.

**Comment by RacerBG** [comment]
> I have no idea what you think the problems here are. It's very unclear and thus probably unactionable.

The body of the text goes up while it should be like the one on the right.

**Comment by RacerBG** [comment]
@razzeee The original issues are fixed, thanks for working on them however the end result have another small issue with horizontal orientation:

![Screenshot_2024-05-19-16-10-19-048_com android chrome](https://github.com/flathub-infra/website/assets/68707872/53c81325-12bd-48f7-aee8-33e0c5ff83b9)

The font should be smaller in my opinion. On vertical orientation everything looks as expected.

**Comment by razzeee** [comment]
I can't reproduce this in firefox or chrome

**Comment by RacerBG** [comment]
> I can't reproduce this in firefox or chrome

My bad, I was using 150% scaling, reverting to 100% fixed it.
