### ISSUE TITLE
App of the day tile papercuts

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#3199]
At narrow sizes the app of the day tiles have a number of issues:

- [x] The "App of the Day" header is part of the left column. This means it wraps awkwardly at narrow sizes, even though there's enough space to its right. I'd make the header its own full-width element at mobile width.

![image](https://github.com/flathub-infra/website/assets/1908896/5df422ea-5fee-432c-977f-2360f1a8c32f)

- [ ] The icon is not vertically centered on the name+summary, which looks especially off with longer summaries:

![image](https://github.com/flathub-infra/website/assets/1908896/784966c6-11d4-4641-97ac-cc1754220e93)

- [x] The summary needs a little bit of padding from the icon on the right, currently they can almost touch, which looks weird. Perhaps it'd also help to use a smaller font size for the summary here?

![image](https://github.com/flathub-infra/website/assets/1908896/44e8f00c-95d2-4ee8-9e6a-0e9138c3bf10)

**Comment by razzeee** [comment]
> The icon is not vertically centered on the name+summary, which looks especially off with longer summaries:

If I'm not misunderstanding this, I've tried it and it made it look weird/broken. As it throws off the balance in that element.

> Perhaps it'd also help to use a smaller font size for the summary here?

Done with the latest changes
