### ISSUE TITLE
Home page trending section: Remember state when going back

### ISSUE THREAD

**Issue by bertob** [flathub-infra/website#3200]
It's a bit annoying when you want to check out multiple apps in e.g. the "New" section that this part of the page resets when you go back. This happens on both desktop with the tabs, and mobile with the dropdown.

- Open flathub.org
- Click one of the non-default tabs in the new trending/popular/new/updated section, e.g. "New"
- Open one of the apps in that section
- Go back in the browser
- You're back on "Trending"

**Comment by razzeee** [comment]
This works fine for me, using the back button in firefox. It also seems to work fine on firefox mobile in android.

**Comment by bertob** [comment]
Are you sure? For me it works in none of those 3:

[Screencast from 2024-05-21 12-40-44.webm](https://github.com/flathub-infra/website/assets/1908896/88d6ea23-ebdf-4b88-b9e7-debe97b04410)

**Comment by razzeee** [comment]
Yeah, seems the same to me now, maybe a deploy from earlier today broke it.

**Comment by RacerBG** [comment]
> Yeah, seems the same to me now, maybe a deploy from earlier today broke it.

It wasn't working at all for me even before that, just like the author of this issue.
