### ISSUE TITLE
App of the Day name is ellipsized on small screens

### ISSUE THREAD

**Issue by gmankab** [flathub-infra/website#3254]
Look at "Forge Spaks" app
One possible solution is to allow word-wrap on screens where there is a lot of vertical space‚ but not a lot of horizontal. Keeping text ellipsized is a no-go for phones since they can't show hints in a usable matter
![IMG_20240524_005506_840](https://github.com/flathub-infra/website/assets/73340745/c15a7b76-b793-47aa-87c5-8d52c6f0b8c5)

**Comment by razzeee** [comment]
What's the used resolution? At some point it becomes "worthless" to optimize this.

**Comment by gmankab** [comment]
> What's the used resolution?

650 x 1280

**Comment by gmankab** [comment]
> What's the used resolution? At some point it becomes "worthless" to optimize this.

this is on postmarket os phone and I assume this shouldn't be too hard to fix

2280x1080

**Comment by razzeee** [comment]
Are you sure? We're using a two column layout when bigger then `1024px` which I don't see in your screenshot. Even when I scale my system to 300% I can't repro this.

https://tailwindcss.com/docs/responsive-design

![image](https://github.com/flathub-infra/website/assets/5943908/866c7542-3159-46a0-b4a6-f7a02fca2867)


I can still look into changing this behaviour, but this seems weird.

**Comment by gmankab** [comment]
thanks
