### ISSUE TITLE
Notify maintainers by email when official builds fail to get published

### ISSUE THREAD

**Issue by guihkx** [flathub-infra/website#3305]
For example, [this official build](https://buildbot.flathub.org/#/builders/6/builds/124476) of a package I maintain, "silently failed" hours ago:

![image](https://github.com/flathub-infra/website/assets/626206/ed46c1cc-65d2-4987-a97c-65224d990488)

---

![image](https://github.com/flathub-infra/website/assets/626206/1bdf971d-d9e3-44d6-a9e0-0e87ee881d9a)

And I only noticed it after I manually went through builds on [buildbot.flathub.org](https://buildbot.flathub.org/).

It'd be great if we (package collaborators) could get an email informing us of such failures, similarly to what GitHub Action does when a workflow run fails.

Thank you.

**Comment by bbhtt** [comment]
This is tracked sepereately on the main repo. It will be moat likely be solved when buildbot is replaced with Github actions.

**Comment by guihkx** [comment]
Thanks for the link!
