### ISSUE TITLE
Keywords from .desktop file not shown if metainfo also contains keywords

### ISSUE THREAD

**Issue by Alexander-Wilms** [flathub-infra/website#3433]
The VCMI .desktop file contains these keywords:

```
Keywords=heroes of might and magic;heroes;homm;homm3;strategy;
```
https://github.com/vcmi/vcmi/blob/9121fcdc975dbf31a8eec8b2a41922402e5321a2/launcher/vcmilauncher.desktop#L14

The metainfo file contains these keywords:
```
	<keywords>
		<keyword>heroes3</keyword>
		<keyword>homm3</keyword>
	</keywords>
```
https://github.com/vcmi/vcmi/blob/9121fcdc975dbf31a8eec8b2a41922402e5321a2/launcher/eu.vcmi.VCMI.metainfo.xml#L143

However, only the latter ones are shown on flathub.org:
![image](https://github.com/flathub-infra/website/assets/3226457/4fb3ff3f-6e38-4d0f-b43c-0f3b23825505)

According to this comment, they should be merged:
 
 https://github.com/ximion/appstream/issues/636#issuecomment-2157018931
 
 First, I thought it might be because the .desktop file contains a keyword with spaces. Not sure if that matters.

**Comment by bbhtt** [comment]
This is an issue with appstream, if it doesn't pull in the keywords from `.desktop` file. It's missing from the catalogue data:

```
gunzip -c ~/.local/share/flatpak/app/eu.vcmi.VCMI/current/active/files/share/app-info/xmls/eu.vcmi.VCMI.xml.gz|xmllint --xpath "//keywords/keyword/text()" -

heroes3
homm3
```
