### ISSUE TITLE
Webps are too compressed

### ISSUE THREAD

**Issue by GeopJr** [flathub-infra/website#3469]
This should probably be raised on the backend, not sure where its issue tracker is, but the webps are too compressed:

| Webp | Png |
| --- | --- |
| ![](https://dl.flathub.org/media/app/drey/Warp/1800937226c0641557c1756136aa0eb4/icons/128x128/app.drey.Warp.webp) | ![](https://dl.flathub.org/media/app/drey/Warp/1800937226c0641557c1756136aa0eb4/icons/128x128/app.drey.Warp.png) |

Very noticeable: 

![image](https://github.com/flathub-infra/website/assets/18014039/91fded81-3083-4af5-9d19-6921273c5908)

![image](https://github.com/flathub-infra/website/assets/18014039/bcf681c8-de51-4a4d-b57b-ffb6b6d726f5)

![image](https://github.com/flathub-infra/website/assets/18014039/1180a01a-de4a-4988-9068-71cfe1340415)

**Comment by razzeee** [comment]
We're back to png for now
