### ISSUE TITLE
Card background tile

### ISSUE THREAD

**Issue by razzeee** [flathub-infra/website#3601]
Can somebody please look at tiling https://github.com/flathub-infra/website/blob/main/frontend/public/img/card-background.webp 

It's way too big and causes our site performance to tank.

@jimmac @bertob @cassidyjames 

![image](https://github.com/user-attachments/assets/b649d16e-3ed6-4c16-801b-00dad3dbe83f)

**Comment by jimmac** [comment]
Would this one work?

![small-pattern-dark](https://github.com/user-attachments/assets/cc9dc612-d01f-4f2c-86dc-24e287a54e79)

**Comment by razzeee** [comment]
Somehow they end up empty when I download them. Can you also use webp please?

**Comment by razzeee** [comment]
Thanks
