### ISSUE TITLE
Add ALT Linux to setup list

### ISSUE THREAD

**Issue by Armatik** [flathub-infra/website#3636]
Please add ALT Linux to the flathub installation list.

To install flathub on ALT Linux, follow these steps:
```
su -
apt-get update
apt-get install flatpak-repo-flathub
```

This package will pull flatpak itself from the repository and configure the flathub repository

**Comment by razzeee** [comment]
Add it on the flatpak docs via a pr please, we only sync with that source.

**Comment by Armatik** [comment]
> Add it on the flatpak docs via a pr please, we only sync with that source.

Good afternoon. Can you tell me how often the information about the systems is updated? System information added to flatpack docs

**Comment by razzeee** [comment]
It's synced on demand/manually - I will do a sync now

**Comment by Armatik** [comment]
> It's synced on demand/manually - I will do a sync now

Thanks!
