### ISSUE TITLE
`flathub.org/setup` is missing CSS.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [flathub-infra/website#3670]
The URI is https://flathub.org/setup. For future reference, a duplicate created using SingleFile is available at https://github.com/user-attachments/files/16469749/Set.Up.Flathub._.Flathub.02_08_2024.12_25_50.zip.

**Comment by razzeee** [comment]
Works fine here, can't reproduce

**Comment by razzeee** [comment]
Changed PC, tried incognito mode and with chromium and they all work.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub-infra/website/issues/3670#issuecomment-2266085988

@razzeee, although a new profile should remove any customisations, to be certain I tried https://download-installer.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central-l10n/firefox-130.0a1.en-GB.linux-x86_64.tar.bz2 too, and it reproduced it:

1.	> ![Screenshot_20240802_223507](https://github.com/user-attachments/assets/8021638c-6077-4129-a99c-ab025c683467)
1.	> ![Screenshot_20240802_223459](https://github.com/user-attachments/assets/77e5161b-7aa4-488f-a1b3-7ae122614272)

If that doesn't demonstrate a problem, I don't know what kind of testbed would. Should I run a VM?

**Comment by razzeee** [comment]
I just tried my fedora rawhide vm and everything seems fine

![image](https://github.com/user-attachments/assets/6ceb47ef-5289-453b-ac10-96128f06f742)

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub-infra/website/issues/3670#issuecomment-2267634188

@razzeee, I'm dumbfounded, then. I definitely launched a portable version that appeared to create a new profile directory inside its PWD. Consequently, where do reckon this should be taken? https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Untriaged?

**Comment by razzeee** [comment]
Did you try different internet access points, just to be sure?

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub-infra/website/issues/3670#issuecomment-2267637178

@razzeee, I'm using a desktop PC, so I can't easily. I'm using 2 x practically unconfigured Teltonika RUTXR1s, though, so I'd be surprised if they were somehow filtering CSS on a single page. However, I tried connecting to ProtonVPN (since it uses encryption) yet the result is identical:

```log
PS /home/RokeJulianLockhart> traceroute 'flathub.org'
traceroute to flathub.org (146.75.73.91), 30 hops max, 60 byte packets
 1  _gateway (10.96.0.1)  59.581 ms  59.627 ms  59.644 ms
 2  unn-169-150-196-124.datapacket.com (169.150.196.124)  59.680 ms  60.370 ms unn-169-150-196-125.datapacket.com (169.150.196.125)  60.221 ms
 3  vl222.ams-eq6-core-2.cdn77.com (185.229.188.212)  60.278 ms vl223.ams-eq6-core-1.cdn77.com (185.229.188.210)  61.073 ms vl224.ams-eq6-core-2.cdn77.com (185.229.188.214)  61.069 ms
 4  ae22-402.ams10.core-backbone.com (81.95.9.42)  61.083 ms ae22-406.ams10.core-backbone.com (81.95.9.44)  61.077 ms  61.086 ms
 5  ae3-2072.lon10.core-backbone.com (80.255.15.166)  65.633 ms  65.662 ms  66.343 ms
```

**Comment by RokeJulianLockhart** [comment]
> ![Screenshot_20240804_224747](https://github.com/user-attachments/assets/33fa2f32-eaf0-4ce2-bf14-71b816555cf8)

It even occurs in a VM.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/flathub-infra/website/issues/3670#issuecomment-2268272898

@razzeee, it appears not, if I'm using the tool correctly:

> ![Screenshot_20240805_141855](https://github.com/user-attachments/assets/d47c7b7e-1812-410c-9fc9-9da33ad2c2fc)

**Comment by razzeee** [comment]
I'm not sure, only idea I have, is that you might have caching disabled, when the network tools are open.

![image](https://github.com/user-attachments/assets/a515eb0a-b7b1-4fa4-9834-c7c09418e988)

Still shouldn't affect multiple browsers.
