### ISSUE TITLE
Add Vanilla OS and Aeon setup instructions

### ISSUE THREAD

**Issue by twihno** [flathub-infra/website#3699]
[Vanilla OS](https://vanillaos.org) released it's first stable release in the 2.x branch.
[Aeon](https://aeondesktop.github.io) is currently RC3.

Both distros heavily promote the usage of flatpak as the preferred way of installing apps.
Even though they don't require any setup IMHO it would be nice to mirror this information on the setup page.

**Comment by razzeee** [comment]
Vanilla OS should start showing up with the next build
