### ISSUE TITLE
Screenshot is downscaled, even when zoomed in

### ISSUE THREAD

**Issue by YaLTeR** [flathub-infra/website#37]
The https://beta.flathub.org/apps/details/org.gnome.gitlab.YaLTeR.VideoTrimmer page shows a downscaled screenshot even when zoomed in:

![image](https://user-images.githubusercontent.com/1794388/155873992-3b075cca-1add-485c-a009-b84c39b8ee08.png)

The image file it links seems already downscaled and with extra transparent padding: https://dl.flathub.org/repo/screenshots/org.gnome.gitlab.YaLTeR.VideoTrimmer-stable/752x423/org.gnome.gitlab.YaLTeR.VideoTrimmer-fd9a1ceec26394cda35f73a3f8c27ec4.png

The original image from metainfo is https://gitlab.gnome.org/YaLTeR/video-trimmer/uploads/e840fa093439348448007197d07c8033/image.png

**Comment by razzeee** [comment]
The source image is only 762 × 657 pixels and we're showing that at 752 x 423.

So the "problem" seems to be, that the appstream conversion takes the width and not the height and converts based on that.

**Comment by razzeee** [comment]
Has been fixed now

**Comment by razzeee** [comment]
Waiting for us to reintroduce libappstream, hopefully without problems this time

**Comment by razzeee** [comment]
This should be fixed again, but needs the app to be rebuild
