### ISSUE TITLE
EOL apps appear as `Uses an end-of-life runtime`

### ISSUE THREAD

**Issue by yakushabb** [flathub-infra/website#3704]
https://flathub.org/apps/io.github.lainsce.Quilter and other EOL apps appear in search results without a clear indication of their EOL status.

![resim](https://github.com/user-attachments/assets/5339b975-687f-42f6-9baf-b6eb4f699ba8)

Source of EOL: https://github.com/flathub/io.github.lainsce.Quilter/blob/master/flathub.json

**Comment by bbhtt** [comment]
That's not EOL then, the last build must have failed.

EOL apps appear like this eg. https://flathub.org/apps/com.irccloud.desktop

![image](https://github.com/user-attachments/assets/d76a1421-37af-4763-b261-a68a0c0cbfb3)


I'll restart the build.

**Comment by bbhtt** [comment]
> other EOL apps appear 

Can you open an issue with a list https://github.com/flathub/flathub/issues?
