### ISSUE TITLE
UI doesn't update fully between navigations

### ISSUE THREAD

**Issue by GeopJr** [flathub-infra/website#3811]
Not sure what an appropriate title would be but here's the problem:

Going from Text Editor (not too much info) to Boxes (a lot of info) (without refreshing) causes the following

https://flathub.org/apps/org.gnome.TextEditor

![image](https://github.com/user-attachments/assets/83072597-0dcb-4eef-a6be-5008ae5e29d6)

https://flathub.org/apps/org.gnome.Boxes

![image](https://github.com/user-attachments/assets/d1c531d9-aeed-4a79-b121-8b716a36fc4c)

Notice how the changelog is missing the 'show more' button (and the text is cut off) and the description is fully visible without a button to toggle it.

Refreshing and doing the opposite causes the reverse:

https://flathub.org/apps/org.gnome.Boxes

![image](https://github.com/user-attachments/assets/d6d6c809-4b36-48c1-abc0-e898992c85fb)

https://flathub.org/apps/org.gnome.TextEditor

![image](https://github.com/user-attachments/assets/69c57a6b-7947-42b0-a462-623354453b49)

Notice that the show more/less buttons are visible even though theres not enough content and the description's height is as long as Boxes' even though text editor's is much smaller

**Comment by razzeee** [comment]
good catch

**Comment by GeopJr** [comment]
I can still reproduce the description issue (show more/less button + description height)

**Comment by razzeee** [comment]
I can't, other then it remembering, the show more button already being clicked. You might have to refresh the page.

**Comment by razzeee** [comment]
thought we we're still talking about releases, sorry

**Comment by razzeee** [comment]
I mentioned that above
