### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by soyersoyer** [flathub-infra/website#3945]
The Trending/Popular/New/Updated buttons are not working with Firefox(+uBlock Origin)

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://o467221.ingest.sentry.io/api/6610580/envelope/?sentry_key=b512f563700847e787e978ae1c15133c&sentry_version=7&sentry_client=sentry.javascript.nextjs%2F8.26.0. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by razzeee** [comment]
I'm using the same setup and it's working fine.

The Cross Origin Request is unrelated to that, that's just optional error reporting, in case you run into problems.

**Comment by soyersoyer** [comment]
Ah ok. Receiving en.json takes more than 12 seconds, maybe that's what's causing the slowiness.
