### ISSUE TITLE
Update for Solus instructions

### ISSUE THREAD

**Issue by EbonJaeger** [flathub-infra/website#4004]
Earlier this year, Solus enabled Flathub by default in the flatpak package, which is also installed by default. While the current Software Center still does not have flatpak support, the team is planning on switching to GNOME Software and KDE Discover, both of which do have integrated flatpak support, and users can install those applications right now.

I was looking at updating the instructions on the webpage myself, but the readme states to make in issue before a pull request, so I figured I'd start with this.

**Comment by razzeee** [comment]
This needs to be addressed in the other repo https://github.com/flatpak/flatpak.github.io

**Comment by razzeee** [comment]
Then we can sync it here

**Comment by EbonJaeger** [comment]
Ah, I see, sorry. Do I need to make an issue over there first, or go straight to pull request once I've made changes?

**Comment by razzeee** [comment]
PR should be fine there

**Comment by razzeee** [comment]
I think this should be done
