### ISSUE TITLE
Do not display screenshots with environment="windows"

### ISSUE THREAD

**Issue by CarlSchwan** [flathub-infra/website#4105]
For example: https://flathub.org/apps/org.kde.neochat the 2 last screenshots should not be displayed because they are marked as for Windows https://invent.kde.org/network/neochat/-/blob/master/org.kde.neochat.appdata.xml?ref_type=heads#L402

**Comment by bbhtt** [comment]
`environment="windows"` does not seem valid according to spec.

https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-screenshots

> Optionally, a screenshot may also have an environment property. This string property denotes the GUI environment the screenshot was recorded in, in the form of {env}:{style}, where {env} is a desktop-environment name in lowercase and {style} is a specific style that the desktop environment recognizes, e.g. light and dark for light and dark themes.

It's not in the form of `env:style`, and Windows is not a DE.

**Comment by razzeee** [comment]
But it's listed in https://github.com/ximion/appstream/blob/main/data/desktop-style-ids.txt

**Comment by bbhtt** [comment]
Yea it's weird, @ximion are env's supposed to strictly follow the format or not?

**Comment by CarlSchwan** [comment]
Also the spec is a bit wrong about `env:style`, for example only `gnome` and `gnome:dark` but not `gnome:light` are allowed because only values in the desktop-style-ids.txt are allowed.

**Comment by bbhtt** [comment]
> Yea it's weird, @ximion are env's supposed to strictly follow the format or not?

Ah I guess this the exact same question as https://github.com/ximion/appstream/issues/667
