### ISSUE TITLE
Search is broken on the site and does not work properly

### ISSUE THREAD

**Issue by ThsUsr** [flathub-infra/website#4142]
The search is broken on the site, for example, open this page https://flathub.org/apps/search?q=local%20AI. Of the first 10 results, only 1 is related to the user's request! Don't you think this is wrong? And even if you use different search and filtering methods, there are still a lot of things in the search results that are not related to the request.
![image](https://github.com/user-attachments/assets/030afd82-ca0e-44fe-ab09-4472c018dfa4)

**Comment by razzeee** [comment]
What do you think is not related? All of these have the `local` or `ai` key word, you need to search with "local ai", if you want to match for that combination

**Comment by ThsUsr** [comment]
> What do you think is not related? All of these have the `local` or `ai` key word, you need to search with "local ai", if you want to match for that combination

Your option will produce only one result, but I need any result that has both words, and not one of them. But thanks anyway, it turns out the site supports such filters, based on your answer I solved my question. This option helped: https://flathub.org/apps/search?q=%22chat%22+%22ai%22

**Comment by razzeee** [comment]
Thats expected:

> `last` returns documents containing all the query terms first. If there are not enough results containing all query terms to meet the requested limit, Meilisearch will remove one query term at a time, starting from the end of the query.

 https://www.meilisearch.com/docs/reference/api/search#last
