### ISSUE TITLE
Improve caption display on mobile 

### ISSUE THREAD

**Issue by razzeee** [flathub-infra/website#4156]
![Screenshot_20241116-123015_Firefox Nightly](https://github.com/user-attachments/assets/ce32ef81-706b-442f-a341-ecc2b0f9cf47)

**Comment by RacerBG** [comment]
I don't want to open a new issue so I will put that here (the new buttons at the about page have some formatting issues on mobile):

![Screenshot_2024-11-08-08-34-32-256_com android chrome](https://github.com/user-attachments/assets/0523a4e9-e116-46f9-b99c-c7514163f246)

![Screenshot_2024-11-08-08-34-41-004_com android chrome](https://github.com/user-attachments/assets/b9d18dcb-dd27-4570-b89c-95d3534dc976)

For context this is from the latest version of Google Chrome.
