### ISSUE TITLE
Screenshots fail to display for net.sourceforge.pdfchain

### ISSUE THREAD

**Issue by nbenitez** [flathub-infra/website#4192]
I'm the maintainer of https://flathub.org/apps/net.sourceforge.pdfchain and I just noticed that although the app has [6 different screenshots](https://github.com/flathub/net.sourceforge.pdfchain/blob/master/net.sourceforge.pdfchain.metainfo.xml#L45-L68), the webpage only displays one screenshot but repeated 6 times.

I presume this is a bug in the cache code, given that all [screenshots have same name](https://github.com/flathub/net.sourceforge.pdfchain/blob/master/net.sourceforge.pdfchain.metainfo.xml#L45-L68) although their paths are different.

**Comment by bbhtt** [comment]
No, it's an issue in appstream because all the links end with the same `/max/max1`. Try dropping that.
