### ISSUE TITLE
`description` always shows "zh_TW"

### ISSUE THREAD

**Issue by ovari** [flathub-infra/website#4229]
https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in

```
  <description xml:lang="zh_TW">
    <p>
      Money Manager Ex (MMEX) 是一款免費、開放原始碼、跨平台、易於使用的個人財務和資金管理軟體。它有助於組織財務並追蹤現金流。
    </p>
    <p>
      MMEX 包含 90% 使用者希望在個人理財應用程式中看到的所有基本功能。設計目標是專注於簡單性和用戶友好性——一個可以每天使用的應用程式。
    </p>
  </description>
```

https://flathub.org/apps/org.moneymanagerex.MMEX

![image](https://github.com/user-attachments/assets/64d0556c-be65-455c-904e-fff59dda5062)

### https://flathub.org/de/apps/org.moneymanagerex.MMEX

![image](https://github.com/user-attachments/assets/6e3709a1-e6b9-4c8e-b5b4-8c65ecdd3e87)

https://flathub.org/hu/apps/org.moneymanagerex.MMEX

![image](https://github.com/user-attachments/assets/afa1001b-024f-4ec5-888f-83d50334d989)

Thank you

**Comment by bbhtt** [comment]
> https://github.com/moneymanagerex/moneymanagerex/blob/master/resources/dist/linux/share/metainfo/org.moneymanagerex.MMEX.metainfo.xml.in

Because they translated it wrong. You have to add `xml:lang` to the `<p>` and `li` tags https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#metainfo-translations
but they added it to `description` tags.

You have to fix the metainfo. The app was not rebuild in a long while because this wouldn't pass validation today.

**Comment by ovari** [comment]
> You have to fix the metainfo. The app was not rebuilt in a long while because this wouldn't pass validation today.

It is 2 days old, built 15 hours ago.

**Comment by bbhtt** [comment]
Ok it doesn't get caught because it's a metainfo template ending in `.in` but it's still wrongly translated.

**Comment by ovari** [comment]
Thank you for your reply. Will the update at https://github.com/moneymanagerex/moneymanagerex/pull/6976, once merged, show the translations correctly? Thank you

**Comment by bbhtt** [comment]
Yes should work, but you have to [patch](https://docs.flatpak.org/en/latest/module-sources.html#patch-sources) it on [Flathub repo](https://github.com/flathub/org.moneymanagerex.MMEX) too or wait for a new release.

**Comment by ovari** [comment]
Could flathub be incorrect as it uses `zh-Hans` and `zh-Hant` instead of `zh_CN` and `zh_TW`, respectively?

https://flathub.org/zh-Hans/apps/org.moneymanagerex.MMEX
https://flathub.org/zh-Hant/apps/org.moneymanagerex.MMEX

**Comment by bbhtt** [comment]
No that's fine, in the metainfo you should use `zh_CN`

**Comment by ovari** [comment]
![image](https://github.com/user-attachments/assets/81037aaf-85c9-4e2c-9ab5-3d65da86c85d)

There seems to be something wrong with Flathub as the translation for `zh` aren't showing correctly for:
```
  <name xml:lang="zh_CN">MMEX资金经理</name>
  <name xml:lang="zh_TW">MMEX資金經理</name>
⋮
  <summary xml:lang="zh_CN">组织财务并跟踪现金流</summary>
  <summary xml:lang="zh_TW">組織財務並跟踪現金流</summary>
⋮
      <caption xml:lang="zh_CN">仪表板</caption>
      <caption xml:lang="zh_TW">儀表板</caption>
```

The `name`, `summary`, and `caption` show correctly for other languages like `de` and `hu` which are shown in screenshots at https://github.com/flathub-infra/website/issues/4229#issue-2707940742

**Comment by bbhtt** [comment]
can you open a separate issue for that? Looks like the locales are not mapped correctly.
