### ISSUE TITLE
Allow `end-of-life` key to support translations

### ISSUE THREAD

**Issue by ovari** [flathub-infra/website#4230]
Please allow `This application is no longer maintained because of personal reasons.` to be translated.

String is shown at:
https://flathub.org/hu/apps/net.jami.Jami
![image](https://github.com/user-attachments/assets/797d0de7-8b89-42f8-a1ae-5d02a150af4f)

Hungarian is showing as 100% translated at:
https://hosted.weblate.org/projects/flathub/frontend/hu/
![image](https://github.com/user-attachments/assets/11c0aa87-7da4-441d-b387-94142f864a13)

Thank you

**Comment by bbhtt** [comment]
That's coming from Flatpak's end of life message, not the website, which does not allow translations.

**Comment by ovari** [comment]
```
{
  "end-of-life": "This application is no longer maintained because of personal reasons."
}
```
https://github.com/flathub/net.jami.Jami/blob/master/flathub.json

**Comment by ovari** [comment]
Can the documentation at https://docs.flathub.org/docs/for-app-authors/maintenance/#end-of-life please be updated to state how to add other languages, such as Hungarian?

Does the following work?
```
{
  "end-of-life": "This application is no longer maintained because…"
  "end-of-life"[hu]: "Ez az alkalmazás már nincs karbantartva, mert…"
}
```

Thank you

**Comment by bbhtt** [comment]
No that end-of-life key does not support translations and neither does Flatpak itself.

**Comment by ovari** [comment]
Allow `end-of-life` key to support translations.

**Comment by bbhtt** [comment]
That's a Flatpak feature request.

**Comment by ovari** [comment]
https://github.com/flatpak/flatpak/issues/6021
