### ISSUE TITLE
zh_CN and zh_TW translations are unused

### ISSUE THREAD

**Issue by ovari** [flathub-infra/website#4231]
https://flathub.org/zh-Hans/apps/org.moneymanagerex.MMEX
https://flathub.org/zh-Hant/apps/org.moneymanagerex.MMEX

![image](https://github.com/user-attachments/assets/ea55b335-ecb9-4f28-a4f6-18b09e09d0d4)

Catalogue data:

```xml
<name xml:lang="zh_CN">MMEX资金经理</name>
<name xml:lang="zh_TW">MMEX資金經理</name>
<summary xml:lang="zh_CN">组织财务并跟踪现金流</summary>
<summary xml:lang="zh_TW">組織財務並跟踪現金流</summary>
```

Thank you

**Comment by razzeee** [comment]
Seems to be fine?

**Comment by bbhtt** [comment]
No, the translations for zh_CN and TW are present but the Hans and Hant pages are not using them for captions and summary.

**Comment by bbhtt** [comment]
Effectively zh_Hans and zh_CN are equivalent although the more correct form would be `zh_Hans_CN`. EG. gnulib considers them equivalent.

Hans and Hant are also less used, which means most of the zh translations are not getting used on the website.

```
grep -r zh_CN flathub-stable-appstream.xml|wc -l
1307
→ grep -r zh_Hans flathub-stable-appstream.xml|wc -l
102
→ grep -r zh_Hans flathub-stable-appstream.xml|wc -l
102
→ grep -r zh_Hant flathub-stable-appstream.xml|wc -l
57
→ grep -r zh_TW flathub-stable-appstream.xml|wc -l
754
```
