### ISSUE TITLE
Distro page linking is broken for setup

### ISSUE THREAD

**Issue by LiamDawe** [flathub-infra/website#4247]
Hi, if you direct link to a distro install page, it's a 500 error.

They only work if you first go to the setup page, then click a distro.

Not great for when linking people to it for their distro...please fix :)

Example: https://flathub.org/setup/Kubuntu

**Comment by user-naa** [comment]
If you go to setup page and click distro and then reload page you also will get 500 Internal Server Error.

**Comment by LiamDawe** [comment]
> If you go to setup page and click distro and then reload page you also will get 500 Internal Server Error.

Expected since reloading is like visiting it directly, so it's the same bug.

**Comment by razzeee** [comment]
Should be better now
